[tool.poetry]
name = "maze solver python"
version = "0.1.0"
description = ""
authors = ["joydeepVector <joydeep.p@vectoredge.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
